# Generated by Django 3.0.7 on 2020-07-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challenges',
            old_name='who_can_participate',
            new_name='rules_of_engagement',
        ),
    ]
