# Generated by Django 3.0.8 on 2020-08-03 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20200709_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='favourite',
            field=models.ManyToManyField(blank=True, editable=False, related_name='fav_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
